word = "This program will tell you which of the 26 letters is present in any word or big number or any thing else"
var1 = "If the letter/number/symbol is present then 'true' will appear next to that letter"
var2 = "If the letter/number/symbol is not present then 'false' will appear next to that letter"
var3 = "This works for numbers and ALMOST all symbols too"
print(word)
print(var1)
print(var2)
name = input("Enter your word:- ")


print("A","a" in name)
print("\n")
print("B","b" in name)
print("\n")
print("C","c" in name)
print("\n")
print("D","d" in name)
print("\n")
print("E","e" in name)
print("\n")
print("F","f" in name)
print("\n")
print("G","g" in name)
print("\n")
print("H","h" in name)
print("\n")
print("I","i" in name)
print("\n")
print("J","j" in name)
print("\n")
print("K","k" in name)
print("\n")
print("L","l" in name)
print("\n")
print("M","m" in name)
print("\n")
print("N","n" in name)
print("\n")
print("O","o" in name)
print("\n")
print("P","p" in name)
print("\n")
print("Q","q" in name)
print("\n")
print("R","r" in name)
print("\n")
print("S","s" in name)
print("\n")
print("T","t" in name)
print("\n")
print("U","u" in name)
print("\n")
print("V","v" in name)
print("\n")
print("W","w" in name)
print("\n")
print("X","x" in name)
print("\n")
print("Y","y" in name)
print("\n")
print("Z","z" in name)

print("\n")
print("\n")




print("A","A" in name)
print("\n")
print("B","B" in name)
print("\n")
print("C","C" in name)
print("\n")
print("D","D" in name)
print("\n")
print("E","E" in name)
print("\n")
print("F","F" in name)
print("\n")
print("G","G" in name)
print("\n")
print("H","H" in name)
print("\n")
print("I","I" in name)
print("\n")
print("J","J" in name)
print("\n")
print("K","K" in name)
print("\n")
print("L","L" in name)
print("\n")
print("M","M" in name)
print("\n")
print("N","N" in name)
print("\n")
print("O","O" in name)
print("\n")
print("P","P" in name)
print("\n")
print("Q","Q" in name)
print("\n")
print("R","R" in name)
print("\n")
print("S","S" in name)
print("\n")
print("T","T" in name)
print("\n")
print("U","U" in name)
print("\n")
print("V","V" in name)
print("\n")
print("W","W" in name)
print("\n")
print("X","X" in name)
print("\n")
print("Y","Y" in name)
print("\n")
print("Z","Z" in name)

print("\n")
print("\n")

print("1","A" in name)
print("\n")
print("2","B" in name)
print("\n")
print("3","C" in name)
print("\n")
print("4","D" in name)
print("\n")
print("5","E" in name)
print("\n")
print("6","F" in name)
print("\n")
print("7","G" in name)
print("\n")
print("8","H" in name)
print("\n")
print("9","I" in name)

print("\n")
print("\n")

print("!","!" in name)
print("\n")
print("@","@" in name)
print("\n")
print("#","#" in name)
print("\n")
print("$","$" in name)
print("\n")
print("%","%" in name)
print("\n")
print("^","^" in name)
print("\n")
print("*","*" in name)
print("\n")
print(")",")" in name)
print("\n")
print("-","-" in name)
print("\n")
print("(","(" in name)
print("\n")
print("_","_" in name)
print("\n")
print("+","+" in name)
print("\n")
print("=","=" in name)
print("\n")
print("[","[" in name)
print("\n")
print("{","{" in name)
print("\n")
print("]","]" in name)
print("\n")
print("}","}" in name)
print("\n")
print(";",";" in name)
print("\n")
print(":",":" in name)
print("\n")
print("'","'" in name)
print("\n")
print(",","," in name)
print("\n")
print("<","<" in name)
print("\n")
print(">",">" in name)
print("\n")
print(".","." in name)
print("\n")
print("/","/" in name)
print("\n")
print("?","?" in name)
print("\n")

print("End")






